AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - spec/**/*
    - vendor/**/*
  DisplayCopNames: true
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Metrics/ClassLength:
  Max: 250
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/EmptyMethod:
  EnforcedStyle: expanded
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
