inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - bin/*
    - db/**/*
    - vendor/**/*
    - lib/tasks/*
  DisplayCopNames: true
Documentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 250
Metrics/LineLength:
  Max: 100
Rails/HttpPositionalArguments:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
Style/ClassAndModuleChildren:
  Enabled: false
