inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Metrics/MethodLength:
  Exclude:
    - 'spec/support/feature_helpers.rb'
    # - 'app/controllers/ambiguity_controller.rb'
    # - 'app/controllers/concerns/ambiguity/year.rb'
    # - 'app/controllers/concerns/ambiguity/year_range.rb'
    # - 'app/controllers/downloads_controller.rb'
    # - 'app/controllers/my_controller.rb'
    # - 'app/controllers/tags_controller.rb'
    # - 'app/helpers/application_helper.rb'
    # - 'app/helpers/navigation_helper.rb'
    # - 'app/helpers/sort_helper.rb'
    # - 'app/helpers/tag_helper.rb'
    # - 'app/services/jamcharts_importer.rb'
    # - 'app/services/show_importer/cli.rb'
    # - 'app/services/show_importer/filename_matcher.rb'
    # - 'app/services/show_importer/orchestrator.rb'
    # - 'app/services/show_importer/track_proxy.rb'
    # - 'app/services/show_importer/track_replacer.rb'


AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - bin/*
    - db/**/*
    - vendor/**/*
    - lib/tasks/*
    - app/controllers/playlists_controller.rb # TODO: Refactor
Documentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb
Metrics/ClassLength:
  Max: 250
Metrics/ModuleLength:
  Max: 250
Metrics/LineLength:
  Max: 100
RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*
RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*
Rails/Exit:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false
RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only
Rails/Output:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
Style/ClassAndModuleChildren:
  Enabled: false
Style/MissingRespondToMissing:
  Exclude:
    - app/services/**/*
