inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - db/**/*
    - vendor/**/*
    - lib/tasks/*
  NewCops: enable
  TargetRubyVersion: 2.7.3

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb
Metrics/ClassLength:
  Max: 250
Metrics/ModuleLength:
  Max: 250
RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*
RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*
Rails/Exit:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false
RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only
RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*
  Max: 4
Rails/Output:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/MissingRespondToMissing:
  Exclude:
    - app/services/**/*
