require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - bin/*
    - db/**/*
    - vendor/**/*
    - lib/tasks/*
    - app/controllers/playlists_controller.rb # TODO: Refactor
Documentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb
Metrics/ClassLength:
  Max: 250
Metrics/MethodLength:
  Exclude:
    - spec/support/feature_helpers.rb
Metrics/ModuleLength:
  Max: 250
Metrics/LineLength:
  Max: 100
RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*
RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*
RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*
Rails/Exit:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false
RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only
Rails/Output:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
Style/ClassAndModuleChildren:
  Enabled: false
Style/MissingRespondToMissing:
  Exclude:
    - app/services/**/*
