require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - bin/**/*
    - config/**/*
    - db/migrate/*
    - db/schema.rb
    - spec/support/**/*
    - vendor/**/*
    - lib/tasks/*

Documentation:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/LineLength:
  Max: 100

RSpec/LetSetup:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
