inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4.4

Style/HashSyntax:
  EnforcedShorthandSyntax: always

FactoryBot/ExcessiveCreateList:
  Enabled: false
RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*
    - spec/requests/**/*
RSpec/IndexedLet:
  Enabled: false
RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*
    - spec/requests/**/*
  Max: 4
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
RSpecRails/HaveHttpStatus: # We use Rack::MockResponse
  Enabled: false
