source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.3"

gem "actionpack-action_caching"
gem "chunky_png"
gem "dalli"
gem "friendly_id"
gem "geocoder"
gem "google-api-client"
gem "grape"
gem "grape-entity"
gem "grape-swagger"
gem "grape-swagger-entity"
gem "jwt"
gem "highline"
gem "nokogiri"
gem "pg"
gem "pg_search"
gem "puma"
gem "rack-cors"
gem "rails"
gem "ruby-mp3info"
gem "ruby-progressbar"
gem "sentry-rails"
gem "sentry-ruby"
gem "sidekiq"
gem "shakapacker"
gem "shrine"
gem "slim"
gem "sorcery"
gem "typhoeus"
gem "waveform"
gem "waveformjson"
gem "will_paginate"

group :development do
  gem "bullet"
  gem "dotenv-rails"
  gem "rubocop-capybara"
  gem "rubocop-factory_bot"
  gem "rubocop-performance"
  gem "rubocop-rails-omakase", require: false
  gem "rubocop-rake"
  gem "rubocop-rspec_rails"
  gem "rubocop-rspec"
  gem "rubocop"
end

group :test do
  gem "capybara"
  gem "capybara-email"
  gem "capybara-screenshot"
  gem "factory_bot_rails"
  gem "faker"
  gem "rspec-rails"
  gem "selenium-webdriver"
  gem "shoulda-matchers"
end
