source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "4.0.0"

gem "actionpack-action_caching"
gem "aws-sdk-s3"
gem "chronic"
gem "friendly_id"
gem "dalli"
gem "dry-initializer"
gem "geocoder"
gem "google-api-client"
gem "googleauth"
gem "grape"
gem "grape-entity"
gem "grape-swagger"
gem "grape-swagger-entity"
gem "htmlentities"
gem "image_processing"
gem "jwt"
gem "mcp"
gem "nokogiri"
gem "ostruct"
gem "pg"
gem "pg_search"
gem "puma"
gem "pstore"
gem "rack-cors"
gem "rails"
# TODO: Remove 0_react_on_rails_patch.rb when gem supports connection_pool 3.0+
gem "react_on_rails"
gem "ruby-mp3info"
gem "ruby-progressbar"
gem "rubyzip"
gem "sentry-rails"
gem "sentry-ruby"
gem "sidekiq"
gem "sidekiq-scheduler"
gem "sitemap_generator"
gem "shakapacker"
gem "sorcery"
gem "typhoeus"
gem "waveform"
gem "will_paginate"

group :development do
  gem "brakeman"
  gem "bullet"
  gem "dotenv-rails"
  gem "rubocop-capybara"
  gem "rubocop-factory_bot"
  gem "rubocop-performance"
  gem "rubocop-rails-omakase"
  gem "rubocop-rake"
  gem "rubocop-rspec_rails"
  gem "rubocop-rspec"
  gem "rubocop"
  gem "webrick"
end

group :test do
  gem "capybara"
  gem "capybara-email"
  gem "capybara-screenshot"
  gem "factory_bot"
  gem "factory_bot_rails"
  gem "faker"
  gem "rspec-rails"
  gem "selenium-webdriver"
  gem "shoulda-matchers"
  gem "simplecov"
end
