import React, { useState } from "react";

const CoverArt = ({ coverArtUrls, albumCoverUrl, openAppModal, size = "small", css, prompt }) => {
  const [isLoaded, setIsLoaded] = useState(false);

  const handleOpenModal = () => {
    if (!openAppModal) return;
    const modalContent = (
      <>
        {albumCoverUrl && (
          <div className="large-album-art">
            <img src={albumCoverUrl} alt="Album cover" />
          </div>
        )}
        {coverArtUrls?.large && (
          <div className="large-album-art mt-3">
            <img src={coverArtUrls?.large} alt="Cover art" />
          </div>
        )}

        {prompt && (
          <div className="box prompt mt-2">
            <p>
              Imagery generated by DALL-E via a prompt (see below) which was generated by ChatGPT using metadata from the show. This image may change as better image generation tools become available.
            </p>

            <p className="has-text-weight-bold mt-3" >{prompt}</p>
          </div>
        )}

      </>
    );
    openAppModal(modalContent);
  };

  const handleImageLoad = () => {
    setIsLoaded(true);
  };

  return (
    <div
      className={`cover-art cover-art-modal-trigger ${isLoaded ? "" : "loading-shimmer"}`}
      onClick={handleOpenModal}
    >
    <img
      src={coverArtUrls?.[size]}
      alt="Cover art"
      className={`${css} cover-art-${size}`}
      onLoad={handleImageLoad}
    />
    </div>
  );
};

export default CoverArt;
