version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Generate .env file for CI
          command: echo RAILS_MASTER_KEY=${RAILS_MASTER_KEY} >> .env.local
      - run: docker-compose pull
      - run: make build
      - run: make start
      - run: docker-compose exec app bundle exec rake db:create db:schema:load
      - run: docker-compose exec app bundle exec rake assets:precompile
      - run: docker-compose exec app bundle exec rspec --format progress --format RspecJunitFormatter -o tmp/rspec/rspec.xml --profile 10
      - store_test_results:
          path: tmp/rspec
      - store_artifacts:
          path: tmp/rspec
          destination: rspec

workflows:
  version: 2
  pipeline:
    jobs:
      - build
