:scheduler:
  :schedule:

    sitemap_refresh:
      cron: "0 3 * * * America/Los_Angeles" # Nightly at 3 AM Pacific Time
      class: SitemapRefreshJob

    album_zip_cleanup:
      cron: "0 2 * * * America/Los_Angeles" # Nightly at 2 AM Pacific Time
      class: AlbumZipCleanupJob

    admin_job_audio_cleanup:
      cron: "30 2 * * * America/Los_Angeles" # Nightly at 2:30 AM Pacific Time
      class: Admin::JobAudioCleanupJob

    unattached_blob_cleanup:
      cron: "15 2 * * * America/Los_Angeles" # Nightly at 2:15 AM Pacific Time
      class: UnattachedBlobCleanupJob

    staging_cleanup:
      cron: "45 2 * * * America/Los_Angeles" # Nightly at 2:45 AM Pacific Time
      class: Admin::StagingCleanupJob

    jamcharts:
      cron: "0 4 * * 1 America/Los_Angeles" # Weekly on Monday at 4 AM Pacific Time
      class: JamchartsJob
