test:
  service: Disk
  root: <%= Rails.root.join("tmp/attachments-test") %>

local:
  service: Disk
  root: <%= ENV["IN_DOCKER"] ? "/content/active_storage" : Rails.root.join("tmp/attachments") %>
  public: true
