export const PLAYER_CONSTANTS = {
  SCRUB_SECONDS: 10,
  PREVIOUS_TRACK_THRESHOLD: 3, // Seconds before restart vs previous
  PRELOAD_THRESHOLD: 10,
  FADE_DURATION: 500,
  PLAY_DELAY: 50,
  POSITION_DELAY: 100,
};
