name: Woke
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  woke:
    name: woke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: woke
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true
